use_frameworks!
inhibit_all_warnings!


target "doordeck-sdk-swift-sample" do
  platform :ios, "10.0"
  pod "QRCodeReader.swift", "~> 10.0"
  pod "ReachabilitySwift", "~> 4.3"
  pod "Alamofire", "~> 4.8"
  pod "SwiftyRSA", "~> 1.5"
  pod "Cache", "~> 5.2"
  pod "Sodium", "~> 0.8"
end

